services:
  robotont:
    build:
      context: .
    container_name: robotont
    env_file:
      - defaults.env
      - settings.env
    ports:
      - "${ROBOTONT_FOXGLOVE_HOST_PORT:-8765}:${ROBOTONT_FOXGLOVE_PORT:-8765}"
      - "${GZ_DISCOVERY_MSG_HOST_PORT:-10317}:${GZ_DISCOVERY_MSG_PORT:-10317}/udp"
      - "${GZ_DISCOVERY_SRV_HOST_PORT:-10318}:${GZ_DISCOVERY_SRV_PORT:-10318}/udp"
    volumes:
      - ./worlds:/ws/worlds:ro
      - ./saved_maps:/ws/saved_maps:rw
      - ./src/robotont_bringup/config:/ws/config:ro
      - ./src/robotont_bringup/worlds:/ws/gazebo_worlds:ro
    stdin_open: true
    tty: true
